# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# name: Java CI with Maven

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v4
#     - name: Go to milestone1 directory
#       run: cd milestone1
#     - name: Set up JDK 17
#       uses: actions/setup-java@v3
#       with:
#         java-version: '17'
#         distribution: 'temurin'
#         cache: maven
#     - name: Start MongoDB
#       uses: supercharge/mongodb-github-action@1.11.0
#       with:
#         mongodb-version: '6.0'
#     - name: Build with Maven
#       run: mvn package
#     - name: Test with Maven
#       run: mvn test

name: Setup Ubuntu Environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install prerequisites
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg2 vim curl openjdk-17-jdk maven netcat

    - name: Import MongoDB public GPG key
      run: |
        wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -

    - name: Add MongoDB repository to sources list
      run: |
        echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list

    - name: Update package list and install MongoDB
      run: |
        sudo apt-get update
        sudo apt-get install -y mongodb-org

    - name: Create necessary directories
      run: |
        sudo mkdir -p /data/db /data/configdb
        sudo chown -R mongodb:mongodb /data/db /data/configdb

    - name: Setup project directory
      run: |
        mkdir -p /project/milestone1
        cp -r milestone1 /project/milestone1
        cp run-fast.sh /project/run-fast.sh

    - name: Run script
      run: |
        cd /project
        sh run-fast.sh

